### ISSUE TITLE
Ask the user to send a code block if code is detected outside of one.

### ISSUE THREAD

**Issue by Salint** [codesupport/old-discord-bot#12]
A small suggestion:
Whenever a user types code(single or multi-line), check if he sent it in a codeblock, if not, delete the message and run the **?codeblock** command to hopefully show the user how to correctly do it.

**Comment by LamboCreeper** [comment]
Won't happen for MVP, but could be useful. Instead of deleting the message we should have it stating that they should use a code block, as we do not want people losing code.

**Comment by Salint** [comment]
Or maybe(not sure if possible) remove it, and let the bot repost it in a codeblock.

**Comment by LamboCreeper** [comment]
It's probably better if we make the user type it out, this means they're more likely to remember it for next time. We can experiment nearer the time.

**Comment by Salint** [comment]
> It's probably better if we make the user type it out, this means they're more likely to remember it for next time. We can experiment nearer the time.

Well, do what you will.
