### ISSUE TITLE
Says "!codeblock" on Rule 9 instead of "?codeblock"

### ISSUE THREAD

**Issue by jacobgasser** [codesupport/old-discord-bot#29]
Matthias has brought it to my attention that there is an issue in Rule 9. It says "When posting code, please use code blocks (see !codeblock for help)." Which is incorrect since the command is "?codeblock"

**Comment by LamboCreeper** [comment]
Good spot, this needs to be fixed to avoid confusion. I'll try get it done by the weekend - will be a quick fix.

**Comment by LamboCreeper** [comment]
See #33.
