### ISSUE TITLE
Add "Deleter" field to "Message Deleted" log entry

### ISSUE THREAD

**Issue by jacobgasser** [codesupport/old-discord-bot#38]
As of right now, this is a current log entry sample, 
![image](https://user-images.githubusercontent.com/43097555/69871988-3e63d580-1282-11ea-9e52-e4a078619d04.png)
There is currently no way to know who deleted that message, was it the user? was it a mod?

There should be an extra field ("deleter") with the member object of who deleted it.

Member Object Example: 
![image](https://user-images.githubusercontent.com/43097555/69872104-90a4f680-1282-11ea-8810-a54ed3b373ed.png)

**Comment by LamboCreeper** [comment]
I've attempted this in the past, but you have to use the audit logs and it ended up being more hassle than what it's worth.

**Comment by jacobgasser** [comment]
No it is going to work.
